const CONFIG = {
AUTO_COTES_URL: "URL_CSV_AUTO_COTES",
HISTORY_URL: "URL_CSV_HISTORY",
PARIS_FORM_URL: "URL_GOOGLE_FORM_PARIS",
DEBT_FORM_URL: "URL_GOOGLE_FORM_DETTES",
ADMIN_PASSWORD: "jokeradmin",
ILLEGAL_PASSWORD: "blackmarket",
DEBT_PASSWORD: "ledger"
};